dbConfig:
  host: "mysql-service"
  user: "root"
  name: "tododb"
backend:
  image:
    repository: "ocaltubitak/todo-kube-backend"
    tag: "b25e1dd"
  resources:
    requests:
      memory: "96Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetMemoryUtilizationPercentage: 70
frontend:
  image:
    repository: "ocaltubitak/todo-kube-frontend"
    tag: "b25e1dd"
