apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-longhorn-pvc
  namespace: todo-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
