{
 "title": "Staj - Kubernetes Cluster Dashboard",
 "tags": [
  "staj",
  "kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Master Node",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 5 },
   "targets": [
    {
     "expr": "kube_node_status_condition{node=\"master-node\",condition=\"Ready\",status=\"true\"}"
    }
   ]
  },
  {
   "title": "Worker Node",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 5 },
   "targets": [
    {
     "expr": "kube_node_status_condition{node=\"worker-node\",condition=\"Ready\",status=\"true\"}"
    }
   ]
  },
  {
   "title": "Deployment CPU Kullanımı",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 5, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum by (workload) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",image!=\"\"}[5m]) * on(namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\",workload_type=\"deployment\"})",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Deployment RAM Kullanımı",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 5, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (workload) (container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"\",image!=\"\"} * on(namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\",workload_type=\"deployment\"})",
     "legendFormat": "{{workload}}"
    }
   ]
  }
 ]
}