apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-configmap
  namespace: todo-app
data:
  DB_HOST: {{ .Values.dbConfig.host | quote }}
  DB_USER: {{ .Values.dbConfig.user | quote }}
  DB_NAME: {{ .Values.dbConfig.name | quote }}